### ISSUE TITLE
Playnite 10 release?

### ISSUE THREAD

**Issue by Jeshibu** [psychonic/Playnite-EmuLibrary#1]
I see there's been a commit for Playnite 10 compatibility, is that still incomplete?

**Comment by psychonic** [comment]
No, it works.

**Comment by Jeshibu** [comment]
Cool! I'd urge you to release it to the [Playnite Addon database](https://github.com/JosefNemec/PlayniteAddonDatabase), so it can be found and installed from within Playnite, or [from the Playnite website](https://playnite.link/addons.html)

**Comment by psychonic** [comment]
I don't have any plans to put any further effort into publishing it. Due to the very narrow use case, it didn't seem to find much use. I barely find the time to finish/update my extensions, much less tidy them up for the very limit publish consumption they do/would get.

I will however continue to push the code updates for this one publicly for as long as convenient.
